name: Scheduled Integration Tests

on:
  schedule:
    # Run at 00:00 and 12:00 UTC every day
    - cron: '0 0,12 * * *'
  workflow_dispatch:
    inputs:
      verbose:
        description: 'Enable verbose logging'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  integration-tests:
    name: API Integration Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Run integration tests
      env:
        PALABRA_CLIENT_ID: ${{ secrets.PALABRA_CLIENT_ID }}
        PALABRA_CLIENT_SECRET: ${{ secrets.PALABRA_CLIENT_SECRET }}
        PALABRA_DEBUG: ${{ github.event.inputs.verbose || 'false' }}
      run: |
        echo "🧪 Running integration tests against Palabra AI API..."
        ./gradlew test --tests "*IntegrationTest" --info --no-daemon
       